# Site settings
title: Tomas Mulder's Portfolio
email: tcmulder@gmail.com
description: A portfolio for Tomas Mulder.
url: "http://www.tcmulder.com" # the base hostname & protocol for your site
twitter_username: tcmulder

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
